### PR TITLE
HOCS-6588 : COMP - Directorate selection doesn't match the value disp…

### PR DESCRIPTION
**Pull request by sameerinfo2003**
JIRA Link : https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6588

### CODE REVIEW

**Comment by robertdeniszczyc2** [comment]
Hi @sameerinfo2003 ,

I've tested this locally and it doesn't seem to have the desired effect unless I have missed something. When I have tested it, the original EUSSFP text can still be seen in the summary and accordion, it isn't being replaced, so there is potentially extra changes required here to alter the display value.

Could you have a look to try to replicate please? Happy to jump on a call if needed to show what I see,

Thanks,
Rob

**Comment by jeff-horton-ho-sas** [comment]
@sameerinfo2003 It looks like hocs-casework is still configured to show directorate options based on OwningCSU, which was removed here: https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6542. The hocs-casework props should match the hocs-workflow props, so the same change will need to be made in hocs-casework.

**Comment by LiamMacP** [comment]
> @sameerinfo2003 It looks like hocs-casework is still configured to show directorate options based on OwningCSU, which was removed here: https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6542. The hocs-casework props should match the hocs-workflow props, so the same change will need to be made in hocs-casework.

They shouldn't always necessarily match, I don't know the context of the ticket, but as some cases have old values we need to support that within the accordion and summary.

**Comment by jeff-horton-ho-sas** [comment]
> > @sameerinfo2003 It looks like hocs-casework is still configured to show directorate options based on OwningCSU, which was removed here: https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6542. The hocs-casework props should match the hocs-workflow props, so the same change will need to be made in hocs-casework.
> 
> They shouldn't always necessarily match, I don't know the context of the ticket, but as some cases have old values we need to support that within the accordion and summary.

Good point. In this case the mappings are still conditional on the OwningCSU value that has been removed. The hocs-casework props need to be changed to a single mapping of values to labels matching the current hocs-workflow props.

**Pull request closed without merging**
